spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

bookstore:
  app:
    jwtSecret: bookstore
    jwtExpirationMs: 300000